apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
  namespace: blog-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-app
  template:
    metadata:
      labels:
        app: blog-app
    spec:
      containers:
        - name: angular-container
          image: sthota04/angularblogapp-img:v11
          ports:
            - containerPort: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: angular-service
  namespace: blog-application
spec:
  selector:
    app: blog-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8086
