apiVersion: apps/v1
kind: Deployment
metadata:
  name: blogpostms-deployment
  namespace: blog-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-app
  template:
    metadata:
      labels:
        app: blog-app
    spec:
      containers: 
        - name: blogpostms-container
          image: sthota04/blogpostimage:v3
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: blogpostms-config
            - secretRef:
                name: blogpostms-secret

---
apiVersion: v1
kind: Service
metadata:
  name: blogpostms-service
  namespace: blog-application
spec:
  selector:
    app: blog-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080